config/routes.rb
Rails.application.routes.draw do
 

  root 'static_pages#home'
  resources :corsairs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
	  validates :first_name, presence: true
	  validates	:age, presence: true
	  validates_numericality_of :age, :greater_than => 15
	  validates :likeness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController
  def index
  	@corsairs = Corsair.all
 	end

  def new
  	@corsair = Corsair.new
  end

  def show
  	@corsair = Corsair.find(params[:id])
  end

	def create
		@corsair = Corsair.new(corsair_params)
		if @corsair.save
		redirect_to @corsair
		else render 'new'
		end
	end

  def edit
  	 @corsair = Corsair.find(params[:id])
  end

  def update
  	@corsair = Corsair.find(params[:id])
		if @corsair.update(corsair_params)
			redirect_to corsairs_path
		else 
			render 'edit'
		end
	end

	def destroy
		@corsair = Corsair.find(params[:id])
		@corsair.destroy
		redirect_to corsairs_path
	end

	private
	def corsair_params
  	params.require(:corsair).permit(:first_name, :age, :likeness)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/_form.html.erb
  <% if @corsair.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@corsair.errors.count, "erreur") %> ont empêché votre profil d'être sauvegardé !
      </h2>
      <ul>
        <% @corsair.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_with model: @corsair, local: true do |form| %>

 <p>
   <%= form.label "Moussaillon, quel est votre prénom ?" %><br>
   <%= form.text_field :first_name %>
 </p>

 <p>
   <%= form.label "Moussaillon, quel âge avez-vous ?" %><br>
   <%= form.number_field :age %>
 </p>
 

 <p> Préférez-vous les Kebab ou le Hummus ? </p>

	<%= form.radio_button :likeness, 'Kebab' %> Kebab, Miam !
	<%= form.radio_button :likeness, 'Hummus' %> Hummus, au calme

 <p>
   <%= form.submit "Je crée mon profil" %>
 </p>

<% end %>

app/views/corsairs/edit.html.erb
<h1>Vous souhaitez modifier votre profile ?</h1>

<%= render 'corsairs/form' %>

<h2>Vous souhaitez supprimer votre profile ?</h2>

<td> <%= link_to "Supprimer votre profil", corsair_path(@corsair),
              method: :delete,
              data: { confirm: 'Etes-vous sûr ?' } %> </td>

<p> Pour retourner à la Home <%= link_to('Par ici!', corsairs_path) %> </p>  

app/views/corsairs/index.html.erb
<h1>Une super liste de moussaillons !! </h1>
 
<table >
  <tr>
    <th>Prénom</th>
    <th>Age</th>
    <th>Préférence alimentaire</th>
  </tr>
 
  <% @corsairs.each do |corsair| %> 
    <tr>
      <td><%= corsair.first_name %></td>
      <td><%= corsair.age %></td>
      <td><%= corsair.likeness %></td>
      <td><%= link_to "Voir le profil", corsair_path(corsair) %></td>
      <td><%= link_to "Editer le profil", edit_corsair_path(corsair) %></td>
      <td> <%= link_to "Supprimer le moussaillon :'(", corsair_path(corsair),
              method: :delete,
              data: { confirm: 'Etes-vous sûr ?' } %> </td>

    </tr>
  <% end %>
</table>

<p> <%= link_to('Rentrez votre profil de Moussaillon !', new_corsair_path ) %> </p> 

app/views/corsairs/new.html.erb
<h1>Nouveau moussaillon, c'est le moment de renseigner votre profile !</h1>

<%= render 'corsairs/form' %>

app/views/corsairs/show.html.erb
<h2> Cher(e) <%= @corsair.first_name %> </h2>

<p> Il semblerait que tu as <%= @corsair.age %> ans ! </p>

<p> Je m'avancerais à dire que tu préfères <%= @corsair.likeness %>

<p> Ces infos sont fausses ? <%= link_to('Modifiez-les ici !', edit_corsair_path) %> </p> 

<p> Pour retourner à la Home <%= link_to('Par ici!', corsairs_path) %> </p> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Index des moussaillons", corsairs_path %></li>
        <li><%= link_to "Nouveau moussaillon", new_corsair_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
 
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>	


  <%= render 'layouts/header'%>
 
  <body style="margin-top: 50px">

    	<div class="container">
    	<%= yield %>
		</div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", corsairs_path, class: "btn btn-lg btn-primary" %>
</div>